version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  order-service:
    build:
      context: ./order
    ports:
      - "8003:8003"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/OrderData

  product-service:
    build:
      context: ./product
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/ProductData

  user-service:
    build:
      context: ./user
    ports:
      - "8002:8002"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/UserData

  gateway-service:
    build:
      context: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - order-service
      - product-service
      - user-service

volumes:
  mongo-data:
